MY DEV ORG/src/objects/DocLink__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Link__c</fullName>
        <label>Inventory Link</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Type__c</fullName>
        <label>Inventory Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DocLink</label>
    <nameField>
        <label>DocLink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MY DEV ORG/src/objects/Inventory__c.object
<CustomObject>
    <description>Child object to Investment to store documentation and other inventory related information.</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <label>Investment</label>
        <referenceTo>Investment__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MY DEV ORG/src/objects/Investment__c.object
<CustomObject>
    <description>Custom object to capture Investment records that are logged to seek approval from Group Approvals</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MY DEV ORG/src/classes/docController.cls
public class docController {
    @AuraEnabled
    public static List<DocLink__c> getHitsC(string recordID) {
        Map<id,Inventory__c> InvMap=new Map<id,Inventory__c>([select id , Document_Type__c from Inventory__c where Investment__c=:recordId]);
        list<Inventory__c> InvList= [select id , Document_Type__c from Inventory__c where Investment__c=:recordId];
        list<id> InvListID = new List<id>();
        for (Inventory__c i: InvList){InvListID.add(i.id);}
        list<ContentDocumentLink> ListDocLink = [select LinkedEntityId, ContentDocumentID from ContentDocumentLink where LinkedEntityId in:InvListID]; 
	    list<id> CDLListID = new List<id>();
		for (ContentDocumentLink cdl: ListDocLink){CDLListID.add(cdl.ContentDocumentId);}
        Map<id,ContentDocument> CDMap=new Map<id,ContentDocument>([select id , Title from ContentDocument where id in:CDLListID]);
        List<DocLink__c> retList = new  List<DocLink__c>();
		for (ContentDocumentLink cdl: ListDocLink){
            ContentDocument c = CDMap.get(cdl.ContentDocumentId);
            Inventory__c i = InvMap.get(cdl.LinkedEntityId);
            DocLink__c d = new DocLink__c(Inventory_Link__c =  i.id,Link__c = cdl.ContentDocumentID, name = c.title, Inventory_Type__c =  i.Document_Type__c );
          	retList.add(d);}
       return retList;
}}