MY DEV ORG/src/objects/Inventory__c.object
<CustomObject>
    <description>Child object to Investment to store documentation and other inventory related information.</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <label>Investment</label>
        <referenceTo>Investment__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MY DEV ORG/src/objects/Investment__c.object
<CustomObject>
    <description>Custom object to capture Investment records that are logged to seek approval from Group Approvals</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MY DEV ORG/src/classes/FileController.cls
public class FileController {
    
@AuraEnabled
		public static List<string> getListDocType() {
			List<string> ListCaseStaus = new list<string>();
			Schema.DescribeFieldResult fieldResult = Inventory__c.Document_Type__c.getDescribe();
			List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
			for( Schema.PicklistEntry f : ple){ListCaseStaus.add(f.getLabel());}
            return ListCaseStaus;}

@AuraEnabled
    	public static Inventory__c saveAPEX(Id parentId, string Dtype, string Fname){
        
        Inventory__c i = new Inventory__c(name = Fname,Document_Type__c = Dtype, Investment__c = parentId );
        insert i;
        return i;}
                                           
    
    @AuraEnabled
    public static Inventory__c saveTheFile(Id parentId, string Inv, String fileName, String base64Data, String contentType) { 
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        system.debug('1 ' + Inv );
        Inventory__c i = new Inventory__c(name = Inv,Investment__c = parentId );
        insert i;
      	system.debug('2 ' + i.id );  
        
        Attachment a = new Attachment();
        system.debug('3 ' +parentId );  
        
        a.parentId = i.id;

        a.Body = EncodingUtil.base64Decode(base64Data);
        a.Name = fileName;
        a.ContentType = contentType;
        
        insert a;
        
        return i;
    }
}