MY DEV ORG/src/objects/Investment__c.object
<CustomObject>
    <description>Custom object to capture Investment records that are logged to seek approval from Group Approvals</description>
    <fields>
        <fullName>Investment_Type__c</fullName>
        <description>Field to track type of investment being made as this will determine approval process and inventory/documentation requirements related to the Investment record.</description>
        <label>Investment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contracts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merger &amp; Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MY DEV ORG/src/objects/Q_A__c.object
<CustomObject>
    <description>Child object to capture and audit questions and answers regarding an investment.</description>
    <fields>
        <fullName>Answers__c</fullName>
        <label>Answers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Investment object</description>
        <label>Investment</label>
        <referenceTo>Investment__c</referenceTo>
        <relationshipLabel>Q&amp;As</relationshipLabel>
        <relationshipName>Q_As</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Q&amp;A</label>
    <nameField>
        <label>Q&amp;A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Q&amp;As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MY DEV ORG/src/classes/qaController.cls
public class qaController {

    @AuraEnabled
    public static List<Q_A__c> getHitsC(string recordID) {
        Investment__c	 i = [select Investment_Type__c from Investment__c	 where id=:recordId];
		list<Q_A__c> glist = [select Answers__c, Questions__c, Investment__r.Investment_Type__c, Investment__r.name, id from  Q_A__c where Investment__r.Investment_Type__c =:i.Investment_Type__c and Investment__r.id !=:recordID];
        return glist;
    }
}